---

- name: adding document root directory
  file:
          path: "{{ dir }}"
          state: directory
          mode: 0755
- name: cloning ecw-api-test
  git:
          repo:  https://bitbucket.org/ecommercewebsites/ecw-api-test.git
          dest: /tmp/ecw-api-test
          clone: yes

- name: Populating document root
  shell: cp -r /tmp/ecw-api-test/* "{{ dir }}"
