---

- name: Adding database
  mysql_db:
          login_user: root
          login_password: "{{ mysql_root_password }}"
          name: "{{ db_name }}"
          state: present

- name: Adding MySQL user
  mysql_user:
          login_user: root
          login_password: "{{ mysql_root_password }}"
          name: "{{ user_name }}"
          host: '%'
          password: "{{ user_password }}"
          priv: "{{ db_name }}.*:ALL"
          state: present

- name: Bind MySQL address to all ips
  shell: sed -ie 's/bind-address/#bind-address/' /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Uploading au_location sql
  copy:
          src: au-locations-15-08-2019.sql.gz
          dest: /tmp/au-locations-15-08-2019.sql.gz

- name: Restoring database
  mysql_db:
          login_user: root
          login_password: "{{ mysql_root_password }}"
          name: "{{ db_name }}"
          state: import
          target: /tmp/au-locations-15-08-2019.sql.gz
